print('What is your first name?')
FirstName = input()
print('What is you last name?')
LastName = input()
print('What is you birthday date?(in dd/mm/yyyy format)')
Date = input()
print("Hello", FirstName, LastName,", welcome to the Motion Detector! Let's start.")
print('Your username is:',FirstName[:3],LastName[:4],Date)
print('Has there been movement in the room? Yes/No')
Movement = input()
print('Movement detected:', Movement)
print('What is temperatue in your room? in °C')
Celsius = input()
Celsius = int(Celsius)
Fahrenheit = (Celsius  * 9/5) + 32
print('The given temperature ',Celsius,' is ',Fahrenheit,' F')